### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by kjjuno** [kjjuno/swagger-compare#18]
**Describe the bug**
I'm getting a warning the Buffer() is deprecated.

**To Reproduce**
use the example from the docs
```
docker run kjjuno/swagger-compare https://raw.githubusercontent.com/kjjuno/swagger-compare/master/test/petstore.yaml https://raw.githubusercontent.com/kjjuno/swagger-compare/master/test/petstore-new.yaml
```

**output**
```
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
version: 1.0.0
deprecated:
  paths:
    /v1/pet:
      post:
        x-replaced-by:
          path: /v2/pet
          verb: post
        x-remove-on: undefined
      put:
        x-replaced-by: undefined
        x-remove-on: 3/4/2019
    /v2/pet:
      post:
        x-replaced-by:
          path: /v3/pet
          verb: post
        x-remove-on: 2/13/2019
```

**Expected behavior**
I shouldn't see a warning about the Buffer(), I should just get the yaml diff.
